version: '3.7'

services:
  web:
    build:
      context: ./src
      dockerfile: Dockerfile-prod
    ports:
      - "6008:80"
    volumes:
      - ./src/public:/usr/share/nginx/html:ro 
    environment:
      - HUGO_ENV=production
